# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20160524_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
