# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_video_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='number',
            field=models.IntegerField(),
        ),
    ]
